# Job Shop Scheduling Parameters Configuration
job_shop:
  n_machines: 3
  n_jobs: 3
  n_lots: 3
  
processing_times:
  t_span: [1, 20]
  
setup_times:
  setup_mode: dependent # Allowed: independent, dependent (to apply sequence-dependent setup times)
  t_span_setup: [50, 100]
  
random:
  seed: 1  # Set to integer for reproducible results
  
fixed_params:
  demand_per_job: 50

shift:
  shift_constraint: True  # True to apply shift constraints
  shift_time: 480  # 8 hours in minutes