name: Ruff

on:
  push:
    branches: ['**']
  pull_request:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11.4
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.4'
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Install dev dependencies only (ruff)
        run: poetry install --only dev --no-interaction --no-ansi
      - name: Ruff lint (no changes)
        run: poetry run ruff check . --diff
      - name: Ruff format check (no changes)
        run: poetry run ruff format . --check
