name: Ruff

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11.4
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.4"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          poetry --version

      - name: Install dev dependencies only (ruff)
        run: |
          poetry install --only dev --no-interaction --no-ansi

      - name: Ruff lint (no changes)
        run: |
          poetry run ruff check . --diff

      - name: Ruff format check (no changes)
        run: |
          poetry run ruff format . --check
