name: Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11.4
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.4"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies (with dev)
        run: poetry install --with dev --no-interaction --no-ansi

      - name: Run tests
        run: poetry run pytest -q
